version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: assetmanager-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: assetmanager
      MYSQL_USER: assetmanager
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=128M
      --max-connections=50
    networks:
      - dev-network

  redis:
    image: redis:7-alpine
    container_name: assetmanager-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - dev-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: assetmanager-phpmyadmin-dev
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: assetmanager
      PMA_PASSWORD: password123
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - dev-network

volumes:
  mysql_data:
  redis_data:

networks:
  dev-network:
    driver: bridge
